### PR TITLE
Add Type of contract indicator

### LINKED ISSUE #8: Hiring (diversity category) - distribution of staff by type of contracts
ref #5

### PR DESCRIPTION
**Pull request by sophie-ulti**
First try adding an indicator.
I Didn't add the detail page yet. 
And I've got a problem of label. So it's still a work in progress I need help on.

cf issue https://github.com/peopledoc/OPE/issues/8

### CODE REVIEW

**Comment by nadege** [comment]
Good job so far ! :tada: 
There is an issue for the feature around detail-page (#25 ), it's not expected from you do it just now.
ping me to find some time, we'll pair on the label problem!

**Review by nadege — APPROVED** [review]
Nice work! Thank you for the contribution :)

**Comment by superette** [comment]
I'd like to add some modification on contract category in csv file

**Comment by nadege** [comment]
(modification for category will be done in another branch)

**Pull request merged**
